### PR TITLE
Fix to work with curio 0.6.0

### PR DESCRIPTION
**Pull request by crubier**
Tested and validated by myself :-)

### CODE REVIEW

**Comment by crubier** [comment]
Also this PR accidentally shadows #2

**Comment by AndreLouisCaron** [comment]
Please merge and release this :-)

**Comment by nchazin** [comment]
I've tested this PR out and it works (for at least our purposes). It would be cool to get this merged and released!

**Comment by geronimo-iia** [comment]
Hello, the last release (1.0.1 ) work with latest version of curio.

**Pull request closed without merging**
